package com.univapay.utils

/**
 * Constants Class contains all the constants used in the application.
 */
object Constants {

    const val API_ENDPOINT = "https://api.univapay.com/"

    const val INTENT_PROCEED_SUCCESS = "PROCEED_SUCCESS"
    const val INTENT_PROCEED_UNDETERMINED = "PROCEED_UNDETERMINED"
    const val INTENT_PROCEED_FAILURE = "INTENT_PROCEED_FAILURE"
    const val INTENT_CHECKOUT_INITIALIZATION_CALLBACK = "INTENT_CHECKOUT_INITIALIZATION_CALLBACK"
    const val INTENT_CHECKOUT_CHARGE_CALLBACK = "CHECKOUT_CHARGE_CALLBACK"
    const val INTENT_CHECKOUT_SUBSCRIPTION_CALLBACK = "CHECKOUT_SUBSCRIPTION_CALLBACK"
    const val INTENT_CHECKOUT_TOKEN_CALLBACK = "CHECKOUT_TOKEN_CALLBACK"
    const val INTENT_CHECKOUT_FINALIZE = "INTENT_CHECKOUT_FINALIZE"

    const val ARG_CHECKOUT_ARGUMENTS = "CHECKOUT_ARGUMENTS"
    const val ARG_CHECKOUT_CONFIGURATION = "CHECKOUT_CONFIGURATION"
    const val ARG_CHECKOUT_CALLBACK_TYPE = "CHECKOUT_CALLBACK_TYPE"
    const val ARG_CHECKOUT_CALLBACK_CHARGE_DETAILS = "CHECKOUT_CALLBACK_CHARGE_DETAILS"
    const val ARG_CHECKOUT_CALLBACK_SUBSCRIPTION_DETAILS = "CHECKOUT_CALLBACK_SUBSCRIPTION_DETAILS"
    const val ARG_CHECKOUT_CALLBACK_TOKEN_DETAILS = "ARG_CHECKOUT_CALLBACK_TOKEN_DETAILS"
    const val ARG_CHECKOUT_CALLBACK_ERROR = "CHECKOUT_CALLBACK_ERROR"
    const val ARG_TRANSACTION_TOKEN_INFO = "TRANSACTION_TOKEN_INFO"
    const val ARG_ADDRESS_DETAILS = "ADDRESS_DETAILS"
    const val ARG_CARD_DETAILS = "CARD_DETAILS"
    const val ARG_SUBSCRIPTION_DETAILS = "SUBSCRIPTION_DETAILS"
    const val ARG_KONBINI_DETAILS = "KONBINI_DETAILS"
    const val ARG_CUSTOMER_TOKENS = "CUSTOMER_TOKENS"
    const val ARG_CUSTOMER_CARD_TOKENS = "CUSTOMER_CARD_TOKENS"
    const val ARG_CUSTOMER_KONBINI_TOKENS = "CUSTOMER_KONBINI_TOKENS"

    const val ARG_CVV_REQUIRED = "CVV_REQUIRED"
    const val ARG_EXCEEDS_THRESHOLD = "EXCEEDS_THRESHOLD"
    const val ARG_PAYMENT_TYPE = "PAYMENT_TYPE"

    // PAYMENT TYPES
    const val PAYMENT_TYPE_CARD = "CARD_PAYMENT"
    const val PAYMENT_TYPE_KONBINI = "KONBINI_PAYMENT"

    // ERRORS
    const val VALIDATION_ERROR = "VALIDATION_ERROR"
    const val REQUIRED_VALUE = "REQUIRED_VALUE"
    const val INVALID_FORMAT = "INVALID_FORMAT"
    const val INVALID_CARD_NUMBER = "INVALID_CARD_NUMBER"
    const val INVALID_CVV = "INVALID_CVV"
    const val INVALID_FORMAT_LENGTH = "INVALID_FORMAT_LENGTH"
    const val INVALID_FORMAT_EMAIL = "INVALID_FORMAT_EMAIL"
    const val INVALID_FORMAT_CURRENCY = "INVALID_FORMAT_CURRENCY"
    const val INVALID_AMOUNT = "INVALID_AMOUNT"
    const val INVALID_FORMAT_COUNTRY = "INVALID_FORMAT_COUNTRY"
    const val NESTED_JSON_NOT_ALLOWED = "NESTED_JSON_NOT_ALLOWED"
    const val INVALID_FORMAT_DATE = "INVALID_FORMAT_DATE"
    const val INVALID_CARD_BRAND = "INVALID_CARD_BRAND"

    // Subscription Status Check Errors
    const val SUBSCRIPTION_FAILED_TO_CONFIRM_ERROR = "Failed to confirm subscription"
    const val SUBSCRIPTION_STATUS_UNVERIFIED_ERROR = "Subscription status is still UNVERIFIED"
    const val SUBSCRIPTION_UNEXPECTED_STATUS_ERROR = "The subscription is in an unexpected status"

    // Charge Status Check Errors
    const val CHARGE_STATUS_PENDING_ERROR = "Charge status is still PENDING"
    const val CHARGE_UNEXPECTED_STATUS_ERROR = "The charge is in an unexpected status"



}
